#-------------------------------
# Site Settings
title: Andrew Getz
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
description: Andrew Getz's Personal Portfolio
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author_name: Andrew Getz


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Blog"
      url: "/blog/"
    - title: "Projects"
      url: "/projects/"
    - title: "Pages"
      submenu:
      - url: "/contact/"
        title: "Contact"

#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-square-x-twitter", link: "https://twitter.com/andrewgetz"}
- {icon: "fa-brands fa-linkedin", link: "https://www.linkedin.com/in/andrew-getz-22880943/"}
- {icon: "fa-brands fa-pinterest", link: "https://pinterest.com"}

# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Andrew Getz. Building Data <span><i>Pipelines & Analysis</i></span> # Add the "span" tag to highlight text.
  hero_description: I’m Andrew, an Analytics Engineer based in Columbus, Ohio. Full-stack data nerd with a passsion for strategic data problems, and building solutions.
  hero_image: "/images/01.jpg"
  hero_button_contact: Get In Touch
  hero_button_about: About Me


#-------------------------------
# Projects Settings
section_projects_title: 👨🏻‍💻 Selected Works


#-------------------------------
# Testimonials Section
section_testimonial_title: 🙂 What Clients Say

testimonial_items:
  - name: "Mahfam Wagner"
    image: "/images/client-1.jpg"
    designation: "Analytics Director"
    link: "https://www.linkedin.com/in/mahfam-wagner/"
    content : "He is always thinking ahead and looking to make improvements everywhere. He is a lifelong learner and is able to bring a new perspective to the table when solving a data problem."

  - name: "Kierra Botosh"
    image: "/images/client-2.jpg"
    designation: "Growth & Community"
    link: "https://facebook.com/"
    content : "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  - name: "Randy Herwitz"
    image: "/images/client-3.jpg"
    designation: "Executive Assistant"
    link: "https://twitter.com/"
    content : "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  - name: "Hanna Franci"
    image: "/images/client-4.jpg"
    designation: "Product Designer"
    link: "https://twitter.com/"
    content : "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"


#-------------------------------
# Blog Section
section_blog_title: 📚 Read Latest Posts
#-------------------------------


# Tags Section
section_tags_title: ✌️ Explore Topics


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: true
  mailchimp_title: Get interesting news
  mailchimp_identifier: us21.list-manage.com/subscribe/post?u=80dd727e597a58959f9e173dc&amp;id=aa72fc8427&amp;f_id=001eeae6f0 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp_input_text: Enter your email address
  mailchimp_background_image: /images/subscribe-bg.jpg


#-------------------------------
# Footer Settings
footer_description: I’m Andrew, an Analytics Engineer based in Columbus, Ohio. Full-stack data nerd with a passsion for strategic data problems, and building solutions.

#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Projects"
      url: "/projects/"
    - url: "/blog/"
      title: "Blog"
    - url: "/contact/"
      title: "Contact"


#-------------------------------
# Contact Settings
contact:
  email: xzblyynw # Add your form_id
  description: If you'd like to connect to talk shop, or you need some help with a project -- please reach out! # Add a description of your form

# NOTE
# Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id